name: tabular_to_gsea_chip
description: Convert tabular data into GSEA-compatible CHIP files.
keywords:
  - GSEA
  - CHIP
  - Bioinformatics
tools:
  - gawk:
      description: |
        GNU Awk (gawk) is a powerful programming language designed for text processing and typically used as a data extraction and reporting tool.
        It is used here to manipulate tabular data and create the CHIP file format.
      homepage: https://www.gnu.org/software/gawk/
      documentation: https://www.gnu.org/software/gawk/manual/
      licence: ["GPL-3.0-or-later"]
input:
  - tsv:
      type: file
      description: |
        Tab-separated values (TSV) file containing data to be converted into a CHIP file.
  - - id:
        type: string
        description: |
          Feature ID attribute in the abundance table as well as in the GTF file (e.g. the gene_id field).
    - symbol:
        type: string
        description: |
          Feature name attribute in the abundance table as well as in the GTF file (e.g. the gene symbol field).
output:
  - chip:
      type: file
      description: Generated GSEA-compatible CHIP file.
      pattern: "*.chip"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@pinin4fjords" # Replace with actual author handles
maintainers:
  - "@nschcolnicov"
